name: Lint

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install dev depenencies
        run: |
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          flake8 ./

      - name: Run isort
        run: |
          isort ./ --check --diff

      - name: Run black
        run: |
          black ./ --check --diff

      - name: Validate python is correct
          /usr/bin/python3 -m compileall -q .

